version: '3.8'

services:
  php-fpm:
    build: ./
    restart: always
    volumes:
      - ../:/app
    working_dir: /app
    networks:
      - app-network
    depends_on:
      - db

  nginx:
    image: nginx:1.27-alpine
    restart: always
    ports:
      - "${NGINX_PORT}:80"
    volumes:
      - ../:/app
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app-network
    depends_on:
      - php-fpm

  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT}:5432"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  pgdata:
